name: Build and upload binaries
on:
  release:
    types: [published]
  push:
permissions:
  contents: read
jobs:
  build:
    name: Build nginx centos7
    runs-on: ['self-hosted']
    container:
      image: centos:7
    steps:
      - name: Install deps
        run: yum -y install gcc gcc-c++ make zlib-devel rpm-build pcre2-devel wget
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build binary
        env:
          NGINX_VERSION: "1.22.1"
          OPENSSL_VERSION: "1.1.1t"
        run: |
          rpm -Uvh http://nginx.org/packages/centos/7/SRPMS/nginx-$NGINX_VERSION-1.el7.ngx.src.rpm
          wget --no-check-certificate https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz -O /tmp/openssl.tar.gz
          tar -xf /tmp/openssl.tar.gz -C /tmp
          mv /tmp/openssl-* /tmp/openssl
          sed -i '/Requires: openssl/d' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i '/BuildRequires: openssl/d' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i 's/\-\-with\-stream_ssl_preread_module/\-\-with\-stream_ssl_preread_module \-\-with\-openssl\=\/tmp\/openssl/' $HOME/rpmbuild/SPECS/nginx.spec
          rpmbuild -ba $HOME/rpmbuild/SPECS/nginx.spec
          /bin/rm $HOME/rpmbuild/RPMS/x86_64/nginx-debuginfo-*.ngx.x86_64.rpm
      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nginx-centos
          path: /github/home/rpmbuild/RPMS/x86_64/nginx-*.ngx.x86_64.rpm
  upload:
    name: Upload release binaries
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write
    runs-on: ['self-hosted']
    container:
      image: centos:7
    steps:
      - name: Install gh cli
        run: |
          yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          yum -y install gh
      - name: Download workflow artifacts
        uses: actions/download-artifact@v3
        with:
          name: nginx-centos
      - name: Upload release artifacts
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "$GITHUB_REF_NAME" nginx-*
