name: Build and upload binaries
on:
  release:
    types: [published]
  push:
permissions:
  contents: read
jobs:
  build:
    name: Build nginx centos
    runs-on: ['self-hosted']
    strategy:
      matrix:
        version: [7, 8]
    container:
      image: centos:${{ matrix.version }}
    steps:
      - name: Install deps
        run: |
          if grep -q 'release 8' /etc/redhat-release ; then sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* ; sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.epel.cloud|g' /etc/yum.repos.d/CentOS-Linux-* ; fi
          yum -y update
          yum -y install gcc gcc-c++ make zlib-devel rpm-build pcre2-devel wget perl perl-IPC-Cmd git libmaxminddb-devel
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build binary
        env:
          NGINX_VERSION: "1.24.0"
          OPENSSL_VERSION: "3.0.9"
          CENTOS_VERSION: ${{ matrix.version }}
        run: |
          rpm -Uvh http://nginx.org/packages/centos/${CENTOS_VERSION}/SRPMS/nginx-${NGINX_VERSION}-1.el${CENTOS_VERSION}.ngx.src.rpm
          wget --no-check-certificate https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz -O /tmp/openssl.tar.gz
          tar -xf /tmp/openssl.tar.gz -C /tmp
          mv /tmp/openssl-* /tmp/openssl
          git clone https://github.com/leev/ngx_http_geoip2_module.git /tmp/ngx_http_geoip2_module.git
          sed -i '/Requires: openssl/d' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i '/BuildRequires: openssl/d' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i 's|--with-stream_ssl_preread_module|--with-stream_ssl_preread_module --with-openssl=/tmp/openssl --add-dynamic-module=/tmp/ngx_http_geoip2_module.git|' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i 's|%{_sbindir}/nginx-debug|%{_sbindir}/nginx-debug\n\n%{_libdir}/nginx/modules/ngx_http_geoip2_module.so\n%{_libdir}/ngx_stream_geoip2_module.so|' $HOME/rpmbuild/SPECS/nginx.spec
          rpmbuild -ba $HOME/rpmbuild/SPECS/nginx.spec
          /bin/rm $HOME/rpmbuild/RPMS/x86_64/nginx-debuginfo-*.ngx.x86_64.rpm
      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nginx-centos
          path: /github/home/rpmbuild/RPMS/x86_64/nginx-*.ngx.x86_64.rpm
  upload:
    name: Upload release binaries
    if: github.event_name == 'release'
    needs: [build]
    permissions:
      contents: write
    runs-on: ['self-hosted']
    container:
      image: centos:7
    steps:
      - name: Install gh cli
        run: |
          yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          yum -y install gh
      - name: Download workflow artifacts
        uses: actions/download-artifact@v3
        with:
          name: nginx-centos
      - name: Upload release artifacts
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "$GITHUB_REF_NAME" nginx-*
