name: Build and upload binaries
on:
  push:
permissions:
  contents: read
jobs:
  build:
    name: Build nginx centos7
    runs-on: ['self-hosted']
    container:
      image: centos:centos7
    steps:
      - name: Install deps
        run: yum -y install gcc gcc-c++ make zlib-devel rpm-build pcre2-devel wget
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build binary
        env:
          NGINX_VERSION: "1.22.1"
          OPENSSL_VERSION: "1.1.1t"
        run: |
          rpm -Uvh http://nginx.org/packages/centos/7/SRPMS/nginx-$NGINX_VERSION-1.el7.ngx.src.rpm
          wget --no-check-certificate https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz -O /tmp/openssl.tar.gz
          tar -xf /tmp/openssl.tar.gz -C /tmp
          mv /tmp/openssl-* /tmp/openssl
          sed -i '/Requires: openssl/d' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i '/BuildRequires: openssl/d' $HOME/rpmbuild/SPECS/nginx.spec
          sed -i 's/\-\-with\-stream_ssl_preread_module/\-\-with\-stream_ssl_preread_module \-\-with\-openssl\=\/tmp\/openssl/' $HOME/rpmbuild/SPECS/nginx.spec
          rpmbuild -ba $HOME/rpmbuild/SPECS/nginx.spec
      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nginx-centos7
          path: $HOME/rpmbuild/RPMS/x86_64/nginx-*-1.el7.ngx.x86_64.rpm
